# Generated by Django 3.0.3 on 2020-03-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.IntegerField(default=0, verbose_name='学号'),
        ),
    ]
